Appointment upd
black8cherry/superMET pull request #12
Opened 2020-12-12 17:45 UTC by and7mw

2020-12-19 08:47 UTC, black8cherry approved these changes

2020-12-19 11:32 UTC, drsgdev requested changes

2020-12-19 11:32 UTC, drsgdev commented on backend-server/src/main/java/com/unn/controller/AppointmentController.java
> +  @GetMapping("/doctor_free/{id}")
Не делай в эндпоинтах подчеркиваний - делай все через /

2020-12-19 11:32 UTC, drsgdev commented on backend-server/src/main/java/com/unn/controller/AppointmentController.java
> +  @GetMapping("/doctor_busy/{id}")
/

2020-12-19 11:32 UTC, drsgdev commented on backend-server/src/main/java/com/unn/controller/AppointmentController.java
> +  @GetMapping("/patient_free/{id}")
/

2020-12-19 11:32 UTC, drsgdev commented on backend-server/src/main/java/com/unn/controller/AppointmentController.java
> +  @GetMapping("/patient_busy/{id}")
/

2020-12-19 18:17 UTC, and7mw commented
изменить конструктор: doctorID и startTime
добавить editAppointment

2020-12-20 13:33 UTC, drsgdev approved these changes

2020-12-20 13:33 UTC, merged