Implementing Schedule Service
black8cherry/superMET pull request #14
Opened 2020-12-12 19:18 UTC by aDanPin

2020-12-12 21:37 UTC, and7mw commented on backend-server/src/main/java/com/unn/model/Schedule.java
> +public class Schedule {
для чего нам нужно создавать отдельную сущность schedule? мне кажется мы можем напрямую работать с calendar.

2020-12-13 18:54 UTC, aDanPin commented on backend-server/src/main/java/com/unn/model/Schedule.java
> +public class Schedule {
Ты не архитектор.

2020-12-13 18:55 UTC, aDanPin commented
@black8cherry @black8cherry @and7mw 
Please review

2020-12-13 19:46 UTC, and7mw commented on backend-server/src/main/java/com/unn/model/Schedule.java
> +public class Schedule {
:(

2020-12-13 19:47 UTC, and7mw commented
@aDanPin порезолвь конфликты пожалуйста

2020-12-13 19:53 UTC, and7mw requested changes

2020-12-13 19:53 UTC, and7mw commented on backend-server/src/main/java/com/unn/model/Calendar.java
> +  public void SetDoctor(Doctor d) {
насколько я знаю все сеттеры и геттеры создаются lombok и их не нужно отдельно прописывать
```
import lombok.Getter;
import lombok.Setter;
```

2020-12-13 19:53 UTC, and7mw commented on backend-server/src/main/java/com/unn/repository/CalendarRepo.java
> +    Optional<Calendar> getByID(Long calendarId);
вроде как тоже есть стандартный метод findById который не нужно определять

2020-12-13 19:53 UTC, and7mw commented on backend-server/src/main/resources/application.properties
> +spring.datasource.url=jdbc:postgresql://localhost:5433/superMet
это не должно коммититься в мастер

2020-12-14 18:22 UTC, aDanPin commented on backend-server/src/main/java/com/unn/model/Calendar.java
> +  public void SetDoctor(Doctor d) {
Done

2020-12-15 08:50 UTC, aDanPin commented on backend-server/src/main/resources/application.properties
> +spring.datasource.url=jdbc:postgresql://localhost:5433/superMet
Испаравил

2020-12-15 08:50 UTC, aDanPin commented on backend-server/src/main/java/com/unn/repository/CalendarRepo.java
> +    Optional<Calendar> getByID(Long calendarId);
Нашел только findById и использовал его

2020-12-18 08:53 UTC, black8cherry reviewed
Убрать сущность schedule, работаем напрямую с calendar
переименовать ScheduleService -> CalendarService
Соответственно и нынешняя логика в сервисе будет изменена

2020-12-18 08:53 UTC, avdkmv commented on backend-server/src/main/java/com/unn/repository/CalendarRepo.java
> +    Optional<Calendar> findDoctorById(Long doctorId);
ты имел ввиду findByDoctorId

2020-12-18 11:36 UTC, aDanPin commented on backend-server/src/main/java/com/unn/repository/CalendarRepo.java
> +    Optional<Calendar> findDoctorById(Long doctorId);
Done

2020-12-18 11:37 UTC, aDanPin commented
@black8cherry  `ScheduleService` -> `CalendarService` 
Please check

2020-12-18 12:41 UTC, black8cherry requested changes, later dismissed

2020-12-18 12:41 UTC, black8cherry commented on backend-server/src/main/java/com/unn/service/ICalendarService.java
> +  Optional<Calendar> createCalendar();
не думаю что нам нужен пустой календарь

2020-12-18 12:41 UTC, black8cherry commented on backend-server/src/main/java/com/unn/service/impl/CalendarService.java
> +  public Optional<Calendar> createCalendar() {
не думаю что нам нужен пустой календарь

2020-12-18 12:41 UTC, black8cherry commented on backend-server/src/main/java/com/unn/service/impl/CalendarService.java
> +    return Optional.empty();
почему не Optional.of(calendar)?

2020-12-18 12:41 UTC, black8cherry commented on backend-server/src/main/java/com/unn/service/impl/CalendarService.java
> +    return Optional.empty();
почему не Optional.of(calendar)?

2020-12-18 12:41 UTC, black8cherry commented on backend-server/src/main/java/com/unn/service/impl/CalendarService.java
> +    // Wthat should I do here?
изменение в мапе Appointments
т.е. опять же берешь по доктору appointments преобразуешь в мапу и заменяешь ею имеющуюся

2020-12-18 12:41 UTC, black8cherry commented on backend-server/src/main/java/com/unn/service/impl/ValidationService.java
> +  public boolean validateWorkTime(int startTime, int endTime) {
стоит добавить startTime и endTime в сущность
и добавление их в сервисе

2020-12-19 11:10 UTC, aDanPin commented on backend-server/src/main/java/com/unn/service/impl/ValidationService.java
> +  public boolean validateWorkTime(int startTime, int endTime) {
Сделал

2020-12-19 11:11 UTC, aDanPin commented on backend-server/src/main/java/com/unn/service/impl/CalendarService.java
> +    // Wthat should I do here?
Сделал

2020-12-19 11:11 UTC, aDanPin commented on backend-server/src/main/java/com/unn/service/impl/CalendarService.java
> +    return Optional.empty();
Исправил

2020-12-19 11:11 UTC, aDanPin commented on backend-server/src/main/java/com/unn/service/impl/CalendarService.java
> +  public Optional<Calendar> createCalendar() {
Исправил

2020-12-19 11:11 UTC, aDanPin commented on backend-server/src/main/java/com/unn/service/ICalendarService.java
> +  Optional<Calendar> createCalendar();
Исправил

2020-12-19 11:24 UTC, drsgdev requested changes

2020-12-19 11:24 UTC, drsgdev commented on backend-server/src/main/java/com/unn/repository/AppointmentRepo.java
> +    Optional<List<Appointment>> findAllByDoctorId(Long doctorId);
public

2020-12-19 11:24 UTC, drsgdev commented on backend-server/src/main/java/com/unn/repository/CalendarRepo.java
> +    Optional<Calendar> findByDoctorId(Long doctorId);
public

2020-12-19 11:24 UTC, drsgdev commented on backend-server/src/main/java/com/unn/service/impl/CalendarService.java
> +  }
В смысле? Здесь надо создавать календарь, а ты его ищешь. Удали этот метод.

2020-12-19 11:24 UTC, drsgdev commented on backend-server/src/main/java/com/unn/service/impl/CalendarService.java
> +        calendar.setAppointments(apm);
Тебе нужно создать их, а не найти в базе. Когда ты создаешь календарь, еще нет нигде записей. Сделай так, чтобы они создавались на две недели(текущая и следующая) на соотв. время(startTime, endTime).

2020-12-19 11:24 UTC, drsgdev commented on backend-server/src/main/java/com/unn/controller/CalendarController.java
> +  private final CalendarService CalendarService;
А где методы?

2020-12-19 14:06 UTC, and7mw requested changes, later dismissed

2020-12-19 14:06 UTC, and7mw commented on backend-server/src/main/java/com/unn/service/impl/CalendarService.java
> +        calendar.setAppointments(apm);
Думаю тут нужно вызывать метод ```createAppointment``` из ```AppointmentService``` он будет сам складывать в таблицу Appointment и возвращать Optional который и можно добавлять в мапу

2020-12-20 13:25 UTC, drsgdev requested changes

2020-12-20 13:25 UTC, drsgdev commented on backend-server/src/main/java/com/unn/service/impl/CalendarService.java
> +      }
Ты не учитываешь выходные

2020-12-20 13:25 UTC, drsgdev commented on backend-server/src/main/java/com/unn/service/impl/CalendarService.java
> +    return calendar;
Сделай обновление раз в неделю

2020-12-20 13:25 UTC, drsgdev commented on backend-server/src/main/java/com/unn/service/impl/CalendarService.java
> +    return calendar;
Встречи тоже надо удалять каскадно

2020-12-20 14:53 UTC, drsgdev requested changes

2020-12-20 14:53 UTC, drsgdev commented on backend-server/src/main/java/com/unn/service/impl/CalendarService.java
> +                    }
Вынеси в функцию

2020-12-20 15:10 UTC, drsgdev approved these changes

2020-12-20 15:11 UTC, and7mw approved these changes

2020-12-20 15:40 UTC, drsgdev approved these changes

2020-12-20 15:40 UTC, merged