AppointmentService and ChatService impemented
black8cherry/superMET pull request #4
Opened 2020-12-06 18:37 UTC by and7mw

2020-12-06 18:40 UTC, and7mw commented on backend-server/src/main/java/com/unn/service/impl/AppointmentService.java
>  public class AppointmentService implements IAppointmentService {
методы newResult заимплементю как только этот метод понадобиться со стороны фронта так как на данный момент не понимаю что он должен делать

2020-12-07 17:30 UTC, black8cherry commented
@and7mw не удаляй файлы для сборки из target

2020-12-07 21:39 UTC, and7mw commented
> @and7mw не удаляй файлы для сборки из target

ревертнул

2020-12-08 03:21 UTC, drsgdev requested changes

2020-12-08 03:21 UTC, drsgdev commented on backend-server/src/main/java/com/unn/repository/ChatRepo.java
> +    Optional<Chat> findByDoctorIdAndPatientId(Doctor doctorId, Patient patientId);
Для этого нужен еще будет индекс в таблице

2020-12-08 03:21 UTC, drsgdev commented on backend-server/src/main/java/com/unn/service/impl/AppointmentService.java
>    }
Для этого дела лучше переименовать поля doctorId и patientId в просто doctor и patient, а в репозитории сделать метод findByDoctorIdAndPatientId(long, long) - сейчас тут лишний поиск по базе

2020-12-08 03:21 UTC, drsgdev commented on backend-server/src/main/java/com/unn/service/impl/AppointmentService.java
> +    appointmentRepo.deleteByDoctorIdAndPatientId(doctorId, patientId);
Читай коммент выше, если сделаешь, как я там написал - это заработает. А так ты передаешь ему id, а ждет он объекты, вот и не удаляет

2020-12-08 03:21 UTC, drsgdev commented on backend-server/src/main/java/com/unn/service/impl/ChatService.java
> +    return chatRepo.findByDoctorIdAndPatientId(doctor.get(), patient.get());
Здесь то же самое, что и в AppointmentService - надо переименовывать поля

2020-12-09 23:59 UTC, drsgdev approved these changes

2020-12-12 14:26 UTC, drsgdev requested changes
Сделай контроллеры к ним

2020-12-12 16:08 UTC, drsgdev requested changes

2020-12-12 16:08 UTC, drsgdev commented on backend-server/src/main/java/com/unn/controller/AppointmentController.java
> +import org.springframework.web.bind.annotation.*;
убери *

2020-12-12 16:08 UTC, drsgdev commented on backend-server/src/main/java/com/unn/controller/AppointmentController.java
> +  @GetMapping("/appointment/{doctorId}/{patientId}")
"/appointment" навешен на контроллером

2020-12-12 16:08 UTC, drsgdev commented on backend-server/src/main/java/com/unn/controller/AppointmentController.java
> +  @DeleteMapping("/appointment/{doctorId}/{patientId}/delete")
и тут

2020-12-12 16:08 UTC, drsgdev commented on backend-server/src/main/java/com/unn/controller/ChatController.java
> +import org.springframework.web.bind.annotation.*;
*

2020-12-12 16:08 UTC, drsgdev commented on backend-server/src/main/java/com/unn/controller/ChatController.java
> +  @GetMapping("/chat/{doctorId}/{patientId}")
+

2020-12-12 16:08 UTC, drsgdev commented on backend-server/src/main/java/com/unn/controller/ChatController.java
> +  @GetMapping("/chat/{id}/add_message/{message}")
+

2020-12-12 16:08 UTC, drsgdev commented on backend-server/src/main/java/com/unn/service/impl/ValidationService.java
> +import com.unn.model.*;
+

2020-12-12 16:23 UTC, drsgdev approved these changes

2020-12-12 16:23 UTC, merged